/** Actions discovered from the production frontends. Do not expose arbitrary globals. */
const API_ACTIONS = Object.freeze({
  adminAddReviewer: adminAddReviewer,
  adminAddUser: adminAddUser,
  adminAssignReviewersBulk: adminAssignReviewersBulk,
  adminBootstrap: adminBootstrap,
  adminDashboard: adminDashboard,
  adminDeleteFinanceDocument: adminDeleteFinanceDocument,
  adminDeleteWork: adminDeleteWork,
  adminDeleteWorkFile: adminDeleteWorkFile,
  adminGetImportBatchDetail: adminGetImportBatchDetail,
  adminGetRegistration: adminGetRegistration,
  adminGetRegistrationSignSheet: adminGetRegistrationSignSheet,
  adminGetReviewConfig: adminGetReviewConfig,
  adminGetReviewer: adminGetReviewer,
  adminGetUserScanHistory: adminGetUserScanHistory,
  adminGetWorkScoreSummary: adminGetWorkScoreSummary,
  adminImportFromGoogleSheet: adminImportFromGoogleSheet,
  adminListFinanceDocuments: adminListFinanceDocuments,
  adminListMealPasses: adminListMealPasses,
  adminListPayments: adminListPayments,
  adminListRegistrations: adminListRegistrations,
  adminListReviewers: adminListReviewers,
  adminListUsers: adminListUsers,
  adminListWorks: adminListWorks,
  adminPreviewMealPass: adminPreviewMealPass,
  adminResendReviewerCreds: adminResendReviewerCreds,
  adminResetAndInitDatabase: adminResetAndInitDatabase,
  adminSaveRegistration: adminSaveRegistration,
  adminSearchDriveFiles: adminSearchDriveFiles,
  adminSeedSampleData: adminSeedSampleData,
  adminSendBatchImportEmails: adminSendBatchImportEmails,
  adminSendDirectEmail: adminSendDirectEmail,
  adminSendIncompleteProfileEmails: adminSendIncompleteProfileEmails,
  adminSendMealPasses: adminSendMealPasses,
  adminToggleReceiptStatus: adminToggleReceiptStatus,
  adminUpdateReceiptInfo: adminUpdateReceiptInfo,
  adminUpdateRegistrationStatus: adminUpdateRegistrationStatus,
  adminUpdateReviewer: adminUpdateReviewer,
  adminUpdateUserStatus: adminUpdateUserStatus,
  adminUpdateWorkStatus: adminUpdateWorkStatus,
  adminUploadBanner: adminUploadBanner,
  adminUploadFinanceDocument: adminUploadFinanceDocument,
  adminUploadWorkFiles: adminUploadWorkFiles,
  adminVerifyPayment: adminVerifyPayment,
  commitImportBatch: commitImportBatch,
  confirmEventScanner: confirmEventScanner,
  emailMyMealPass: emailMyMealPass,
  exportPaymentsToExcel: exportPaymentsToExcel,
  exportRegistrationsToExcel: exportRegistrationsToExcel,
  exportWorksToExcel: exportWorksToExcel,
  getAdminSettings: getAdminSettings,
  getEventScannerBootstrap: getEventScannerBootstrap,
  getEventScannerRecent: getEventScannerRecent,
  getMealPass: getMealPass,
  getPublicBootstrap: getPublicBootstrap,
  getPublicFinanceDocuments: getPublicFinanceDocuments,
  inspectEventScanner: inspectEventScanner,
  listImportBatches: listImportBatches,
  loginUser: loginUser,
  logoutUser: logoutUser,
  lookupRegistrationForEdit: lookupRegistrationForEdit,
  registerNewUser: registerNewUser,
  replaceWorkFile: replaceWorkFile,
  requestPasswordReset: requestPasswordReset,
  reviewerBootstrap: reviewerBootstrap,
  reviewerGetAssignment: reviewerGetAssignment,
  reviewerSaveReview: reviewerSaveReview,
  saveAdminSettings: saveAdminSettings,
  saveRegistrationEdit: saveRegistrationEdit,
  submitRegistration: submitRegistration,
  submitWork: submitWork,
  uploadExcelForImport: uploadExcelForImport,
  uploadPaymentSlip: uploadPaymentSlip,
  verifyWorkAccess: verifyWorkAccess
});

const API_WRITE_ACTIONS = Object.freeze({
  adminAddReviewer:1, adminAddUser:1, adminAssignReviewersBulk:1, adminDeleteFinanceDocument:1, adminDeleteWork:1, adminDeleteWorkFile:1,
  adminImportFromGoogleSheet:1, adminResendReviewerCreds:1, adminSaveRegistration:1, adminSendBatchImportEmails:1, adminSendDirectEmail:1,
  adminSendIncompleteProfileEmails:1, adminSendMealPasses:1, adminToggleReceiptStatus:1, adminUpdateReceiptInfo:1, adminUpdateRegistrationStatus:1,
  adminUpdateReviewer:1, adminUpdateUserStatus:1, adminUpdateWorkStatus:1, adminUploadBanner:1, adminUploadFinanceDocument:1, adminUploadWorkFiles:1,
  adminVerifyPayment:1, commitImportBatch:1, confirmEventScanner:1,
  emailMyMealPass:1, loginUser:1, logoutUser:1, registerNewUser:1,
  replaceWorkFile:1, requestPasswordReset:1, reviewerSaveReview:1,
  saveAdminSettings:1, saveRegistrationEdit:1, submitRegistration:1,
  submitWork:1, uploadExcelForImport:1, uploadPaymentSlip:1
});
